/**
 * Knowledge Base Constants
 * Mock data and constants for knowledge base management
 */

import { FileType, EducationLevel, Subject, type KnowledgeBaseFile } from '../types';

export const MOCK_KNOWLEDGE_BASE_FILES: KnowledgeBaseFile[] = [
  {
    id: '1',
    fileName: 'Content_C3A_Cycles_P3_Animal Life Cycle.pdf',
    fileType: FileType.CONTENT,
    level: EducationLevel.PRIMARY_3,
    subject: Subject.SCIENCE,
    sizeKB: 245,
    uploadedAt: new Date('2024-01-15'),
    lastModified: new Date('2024-02-20'),
    description: 'Comprehensive guide on animal life cycles for Primary 3 students',
  },
  {
    id: '2',
    fileName: 'Content_C3P_Cycles_P3_Plant Life Cycle.pdf',
    fileType: FileType.CONTENT,
    level: EducationLevel.PRIMARY_3,
    subject: Subject.SCIENCE,
    sizeKB: 198,
    uploadedAt: new Date('2024-01-15'),
    lastModified: new Date('2024-02-20'),
    description: 'Plant life cycles and photosynthesis basics',
  },
  {
    id: '3',
    fileName: 'Content_D3L_Diversity_P3_Living and Non-living Things.pdf',
    fileType: FileType.CONTENT,
    level: EducationLevel.PRIMARY_3,
    subject: Subject.SCIENCE,
    sizeKB: 312,
    uploadedAt: new Date('2024-01-16'),
    lastModified: new Date('2024-02-21'),
    description: 'Characteristics of living and non-living things',
  },
  {
    id: '4',
    fileName: 'Content_D3M_Diversity_P3_Materials.pdf',
    fileType: FileType.CONTENT,
    level: EducationLevel.PRIMARY_3,
    subject: Subject.SCIENCE,
    sizeKB: 287,
    uploadedAt: new Date('2024-01-16'),
    lastModified: new Date('2024-02-21'),
    description: 'Properties and uses of different materials',
  },
  {
    id: '5',
    fileName: 'QB_C3A_Cycles_P3_Animal Life Cycle.pdf',
    fileType: FileType.QUESTION_BANK,
    level: EducationLevel.PRIMARY_3,
    subject: Subject.SCIENCE,
    sizeKB: 156,
    uploadedAt: new Date('2024-01-18'),
    lastModified: new Date('2024-02-25'),
    description: 'Practice questions on animal life cycles',
  },
  {
    id: '6',
    fileName: 'QB_C3P_Cycles_P3_Plant Life Cycle.pdf',
    fileType: FileType.QUESTION_BANK,
    level: EducationLevel.PRIMARY_3,
    subject: Subject.SCIENCE,
    sizeKB: 142,
    uploadedAt: new Date('2024-01-18'),
    lastModified: new Date('2024-02-25'),
    description: 'Plant life cycle assessment questions',
  },
  {
    id: '7',
    fileName: 'QB_D3L_Diversity_P3_Living and Non-living.pdf',
    fileType: FileType.QUESTION_BANK,
    level: EducationLevel.PRIMARY_3,
    subject: Subject.SCIENCE,
    sizeKB: 178,
    uploadedAt: new Date('2024-01-19'),
    lastModified: new Date('2024-02-26'),
    description: 'Quiz on living and non-living classification',
  },
  {
    id: '8',
    fileName: 'Content_M4A_Fractions_P4_Introduction.pdf',
    fileType: FileType.CONTENT,
    level: EducationLevel.PRIMARY_4,
    subject: Subject.MATHEMATICS,
    sizeKB: 423,
    uploadedAt: new Date('2024-01-20'),
    lastModified: new Date('2024-03-01'),
    description: 'Introduction to fractions and basic operations',
  },
  {
    id: '9',
    fileName: 'Content_M4D_Decimals_P4_Basics.pdf',
    fileType: FileType.CONTENT,
    level: EducationLevel.PRIMARY_4,
    subject: Subject.MATHEMATICS,
    sizeKB: 389,
    uploadedAt: new Date('2024-01-20'),
    lastModified: new Date('2024-03-01'),
    description: 'Decimal numbers and place value',
  },
  {
    id: '10',
    fileName: 'QB_M4A_Fractions_P4_Practice.pdf',
    fileType: FileType.QUESTION_BANK,
    level: EducationLevel.PRIMARY_4,
    subject: Subject.MATHEMATICS,
    sizeKB: 234,
    uploadedAt: new Date('2024-01-22'),
    lastModified: new Date('2024-03-05'),
    description: 'Fractions practice problems with solutions',
  },
  {
    id: '11',
    fileName: 'Assessment_S3_Science_P3_Term1.pdf',
    fileType: FileType.ASSESSMENT,
    level: EducationLevel.PRIMARY_3,
    subject: Subject.SCIENCE,
    sizeKB: 512,
    uploadedAt: new Date('2024-02-01'),
    lastModified: new Date('2024-02-15'),
    description: 'Term 1 comprehensive science assessment',
  },
  {
    id: '12',
    fileName: 'Assessment_M4_Mathematics_P4_Term1.pdf',
    fileType: FileType.ASSESSMENT,
    level: EducationLevel.PRIMARY_4,
    subject: Subject.MATHEMATICS,
    sizeKB: 478,
    uploadedAt: new Date('2024-02-01'),
    lastModified: new Date('2024-02-15'),
    description: 'Term 1 mathematics assessment paper',
  },
  {
    id: '13',
    fileName: 'Resource_E5_Grammar_P5_Tenses.pdf',
    fileType: FileType.RESOURCE,
    level: EducationLevel.PRIMARY_5,
    subject: Subject.ENGLISH,
    sizeKB: 356,
    uploadedAt: new Date('2024-02-05'),
    lastModified: new Date('2024-03-10'),
    description: 'Comprehensive guide to English tenses',
  },
  {
    id: '14',
    fileName: 'Resource_E5_Vocabulary_P5_Advanced.pdf',
    fileType: FileType.RESOURCE,
    level: EducationLevel.PRIMARY_5,
    subject: Subject.ENGLISH,
    sizeKB: 298,
    uploadedAt: new Date('2024-02-05'),
    lastModified: new Date('2024-03-10'),
    description: 'Advanced vocabulary building exercises',
  },
  {
    id: '15',
    fileName: 'Content_H6_WorldWar2_P6_Overview.pdf',
    fileType: FileType.CONTENT,
    level: EducationLevel.PRIMARY_6,
    subject: Subject.HISTORY,
    sizeKB: 645,
    uploadedAt: new Date('2024-02-10'),
    lastModified: new Date('2024-03-15'),
    description: 'World War 2 historical overview and key events',
  },
];

export const FILE_TYPE_LABELS: Record<FileType, string> = {
  [FileType.CONTENT]: 'Content',
  [FileType.QUESTION_BANK]: 'Question Bank',
  [FileType.ASSESSMENT]: 'Assessment',
  [FileType.RESOURCE]: 'Resource',
};

export const FILE_TYPE_COLORS: Record<FileType, string> = {
  [FileType.CONTENT]: 'bg-blue-100 text-blue-800',
  [FileType.QUESTION_BANK]: 'bg-purple-100 text-purple-800',
  [FileType.ASSESSMENT]: 'bg-orange-100 text-orange-800',
  [FileType.RESOURCE]: 'bg-green-100 text-green-800',
};
