/**
 * Complaint Center Constants and Mock Data
 */

import type { Complaint } from '../types';
import { ComplaintStatus, ComplaintPriority } from '../types';

export const DEFAULT_PAGE_SIZE = 10;

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: '1',
    date: '2024-12-18',
    complaint: 'The bot provided inappropriate language during our math lesson',
    flaggedMessage: 'Your answer is completely wrong and stupid',
    studentUsername: 'alex_learner',
    studentEmail: 'alex@student.com',
    parentEmail: 'parent_alex@example.com',
    status: ComplaintStatus.PENDING,
    priority: ComplaintPriority.HIGH,
    assignedTo: null,
    createdAt: '2024-12-18T10:30:00Z',
    updatedAt: '2024-12-18T10:30:00Z',
    notes: '',
  },
  {
    id: '2',
    date: '2024-12-17',
    complaint: 'Bot gave factually incorrect information about historical events',
    flaggedMessage: 'World War II started in 1950',
    studentUsername: 'emma_student',
    studentEmail: 'emma@student.com',
    parentEmail: 'parent_emma@example.com',
    status: ComplaintStatus.IN_REVIEW,
    priority: ComplaintPriority.MEDIUM,
    assignedTo: 'Admin John',
    createdAt: '2024-12-17T14:20:00Z',
    updatedAt: '2024-12-17T16:45:00Z',
    notes: 'Investigating the training data for this response',
  },
  {
    id: '3',
    date: '2024-12-17',
    complaint: 'Bot refused to help with legitimate homework question',
    flaggedMessage: 'I cannot help you with that assignment',
    studentUsername: 'james_l',
    studentEmail: 'james@student.com',
    parentEmail: 'parent_james@example.com',
    status: ComplaintStatus.RESOLVED,
    priority: ComplaintPriority.LOW,
    assignedTo: 'Admin Sarah',
    createdAt: '2024-12-17T09:15:00Z',
    updatedAt: '2024-12-17T18:30:00Z',
    notes: 'False positive - question was against policy',
  },
  {
    id: '4',
    date: '2024-12-16',
    complaint: 'Bot displayed biased content during social studies discussion',
    flaggedMessage: 'This political party is always wrong',
    studentUsername: 'sophia_k',
    studentEmail: 'sophia@student.com',
    parentEmail: 'parent_sophia@example.com',
    status: ComplaintStatus.IN_REVIEW,
    priority: ComplaintPriority.URGENT,
    assignedTo: 'Admin John',
    createdAt: '2024-12-16T13:45:00Z',
    updatedAt: '2024-12-17T08:00:00Z',
    notes: 'Escalated to content moderation team',
  },
  {
    id: '5',
    date: '2024-12-16',
    complaint: 'Bot was unresponsive and kept repeating the same answer',
    flaggedMessage: 'Let me help you with that. Let me help you with that.',
    studentUsername: 'oliver_m',
    studentEmail: 'oliver@student.com',
    parentEmail: 'parent_oliver@example.com',
    status: ComplaintStatus.RESOLVED,
    priority: ComplaintPriority.MEDIUM,
    assignedTo: 'Admin Sarah',
    createdAt: '2024-12-16T11:20:00Z',
    updatedAt: '2024-12-16T15:30:00Z',
    notes: 'Technical glitch - fixed in latest update',
  },
  {
    id: '6',
    date: '2024-12-15',
    complaint: 'Bot shared personal information without consent',
    flaggedMessage: 'Your parent\'s email is parent_lily@example.com',
    studentUsername: 'lily_w',
    studentEmail: 'lily@student.com',
    parentEmail: 'parent_lily@example.com',
    status: ComplaintStatus.PENDING,
    priority: ComplaintPriority.URGENT,
    assignedTo: null,
    createdAt: '2024-12-15T16:10:00Z',
    updatedAt: '2024-12-15T16:10:00Z',
    notes: '',
  },
  {
    id: '7',
    date: '2024-12-15',
    complaint: 'Bot provided answers for test questions',
    flaggedMessage: 'Here is the complete answer to question 5 on your test',
    studentUsername: 'noah_p',
    studentEmail: 'noah@student.com',
    parentEmail: 'parent_noah@example.com',
    status: ComplaintStatus.DISMISSED,
    priority: ComplaintPriority.LOW,
    assignedTo: 'Admin Sarah',
    createdAt: '2024-12-15T10:05:00Z',
    updatedAt: '2024-12-15T14:20:00Z',
    notes: 'Student admitted to trying to cheat - not bot error',
  },
  {
    id: '8',
    date: '2024-12-14',
    complaint: 'Bot used outdated scientific information',
    flaggedMessage: 'There are 9 planets in our solar system',
    studentUsername: 'ava_r',
    studentEmail: 'ava@student.com',
    parentEmail: 'parent_ava@example.com',
    status: ComplaintStatus.RESOLVED,
    priority: ComplaintPriority.MEDIUM,
    assignedTo: 'Admin John',
    createdAt: '2024-12-14T12:30:00Z',
    updatedAt: '2024-12-14T17:45:00Z',
    notes: 'Knowledge base updated with latest scientific consensus',
  },
  {
    id: '9',
    date: '2024-12-14',
    complaint: 'Bot made insensitive comments about student\'s learning pace',
    flaggedMessage: 'You should understand this by now, it\'s very basic',
    studentUsername: 'ethan_h',
    studentEmail: 'ethan@student.com',
    parentEmail: 'parent_ethan@example.com',
    status: ComplaintStatus.IN_REVIEW,
    priority: ComplaintPriority.HIGH,
    assignedTo: 'Admin Sarah',
    createdAt: '2024-12-14T09:25:00Z',
    updatedAt: '2024-12-15T11:00:00Z',
    notes: 'Reviewing tone and empathy in responses',
  },
  {
    id: '10',
    date: '2024-12-13',
    complaint: 'Bot promoted external website without verification',
    flaggedMessage: 'You can find better answers at www.randomsite.com',
    studentUsername: 'mia_b',
    studentEmail: 'mia@student.com',
    parentEmail: 'parent_mia@example.com',
    status: ComplaintStatus.PENDING,
    priority: ComplaintPriority.HIGH,
    assignedTo: null,
    createdAt: '2024-12-13T15:40:00Z',
    updatedAt: '2024-12-13T15:40:00Z',
    notes: '',
  },
  {
    id: '11',
    date: '2024-12-13',
    complaint: 'Bot didn\'t respect student\'s preferred learning style',
    flaggedMessage: 'Here is a long text explanation',
    studentUsername: 'lucas_g',
    studentEmail: 'lucas@student.com',
    parentEmail: 'parent_lucas@example.com',
    status: ComplaintStatus.DISMISSED,
    priority: ComplaintPriority.LOW,
    assignedTo: 'Admin John',
    createdAt: '2024-12-13T08:50:00Z',
    updatedAt: '2024-12-13T12:15:00Z',
    notes: 'Student can adjust preferences in settings',
  },
  {
    id: '12',
    date: '2024-12-12',
    complaint: 'Bot suggested unauthorized use of AI tools',
    flaggedMessage: 'You can use ChatGPT to write your essay',
    studentUsername: 'isabella_c',
    studentEmail: 'isabella@student.com',
    parentEmail: 'parent_isabella@example.com',
    status: ComplaintStatus.RESOLVED,
    priority: ComplaintPriority.URGENT,
    assignedTo: 'Admin Sarah',
    createdAt: '2024-12-12T14:15:00Z',
    updatedAt: '2024-12-13T09:30:00Z',
    notes: 'Added safeguards against suggesting policy violations',
  },
];

// Status filter options for dropdown
export const STATUS_FILTER_OPTIONS = [
  { value: 'all', label: 'All Status' },
  { value: ComplaintStatus.PENDING, label: 'Pending' },
  { value: ComplaintStatus.IN_REVIEW, label: 'In Review' },
  { value: ComplaintStatus.RESOLVED, label: 'Resolved' },
  { value: ComplaintStatus.DISMISSED, label: 'Dismissed' },
];

// Priority options
export const PRIORITY_OPTIONS = [
  { value: ComplaintPriority.LOW, label: 'Low' },
  { value: ComplaintPriority.MEDIUM, label: 'Medium' },
  { value: ComplaintPriority.HIGH, label: 'High' },
  { value: ComplaintPriority.URGENT, label: 'Urgent' },
];
